import {Vue} from "nuxt-property-decorator";

Vue.prototype.$lang = "jp";

Vue.prototype.$words = {
  add: {jp: "追加", en: "Add"},
  delete: {jp: "削除", en: "Delete"},
  path: {jp: "Path", en: "Path"},
  readme: {jp: "Readme", en: "Readme"},
  universal: {jp: "汎用", en: "Universal"},
  bg: {jp: "背景", en: "Background"},
  sp: {jp: "モバイル", en: "Mobile"},
  url: {jp: "URL", en: "URL"},
  col: {jp: "カラム幅", en: "Column Size"},
  settings: {jp: "設定", en: "Settings"},
  lat: {jp: "緯度(lat)", en: "lat"},
  lng: {jp: "経度(lng)", en: "lng"},
  marker: {jp: "マーカー", en: "marker"},
  complete: {jp: "完了", en: "Complete"},
  explorer: {jp: "一覧", en: "Explorer"},
  upload: {jp: "アップロード", en: "Upload"},
  sub: {jp: "サブ", en: "sub"},
  text: {jp: "テキスト", en: "Text"},
  more: {jp: "もっと見る", en: "more"},
  news: {jp: "ニュース", en: "News"},
  root: {jp: "基底アイテムデータ", en: "Root Item"},
  page: {jp: "ページ", en: "Page"},
  structure: {jp: "構造", en: "Structure"},
  class: {jp: "クラス", en: "class"},
  id: {jp: "ID", en: "ID"},
  name: {jp: "名前", en: "name"},
  dataClean: {jp: "未使用データ削除", en: "Data Clean"},
  export: {jp: "書き出し", en: "Export"},
  import: {jp: "読み込み", en: "Import"},
  login: {jp: "ログイン", en: "Login"},
  logout: {jp: "ログアウト", en: "Logout"},
  mail: {jp: "メールアドレス", en: "mail"},
  password: {jp: "パスワード", en: "password"},
  description: {jp: "説明", en: "Description"},
  display: {jp: "表示用", en: "Display"},
  itemId: {jp: "アイテムID", en: "itemId"},
  ogp: {jp: "OGP", en: "OGP"},
  alt: {jp: "代替テキスト", en: "alt"},
  src: {jp: "画像URL", en: "src"},
  center: {jp: "中央", en: "center"},
  color: {jp: "カラー", en: "Color"},
  container: {jp: "コンテンツ幅", en: "Contents "},
  fluid: {jp: "fluid", en: "fluid"},
  left: {jp: "左", en: "left"},
  right: {jp: "右", en: "right"},
  theme: {jp: "テーマ", en: "Theme"},
  csv: {jp: "CSV", en: "CSV"},
  editer: {jp: "Editer", en: "Editer"},
  source: {jp: "Source", en: "Source"},
  title: {jp: "タイトル", en: "Title"},
  section: {jp: "セクション", en: "section"},
  meta: {jp: "メタ", en: "Meta"},
  save: {jp: "保存", en: "Save"},
  edit: {jp: "編集", en: "Edit"},
  preview: {jp: "プレビュー", en: "Preview"},
  list: {jp: "一覧", en: "List"},
  image: {jp: "画像", en: "Image"},
  border: {jp: "枠線", en: "Border"},
  align: {jp: "行揃", en: "Align"},
  auto: {jp: "自動", en: "Auto"},
  default: {jp: "初期値", en: "Default"},
  false: {jp: "×", en: "FALSE"},
  true: {jp: "〇", en: "TRUE"},
  module: {jp: "モジュール", en: "module"},
  data: {jp: "データ", en: "Data"},
  date: {jp: "日付", en: "Date"},
  tag: {jp: "タグ", en: "Tag"},
  report: {jp: "活動報告", en: "Report"},
  information: {jp: "お知らせ", en: "Information"},
  directory: {jp: "ディレクトリ", en: "Directory"},
  option: {jp: "オプション", en: "Option"},
  change: {jp: "変更", en: "Change"},
  cannot: {jp: "不可", en: "Can not"},
  box: {jp: "ボックス", en: "Box"},
  donotExport: {jp: "書き出さない", en: "Do not export"},
  hide: {jp: "非表示", en: "hide"},
  ui: {jp: "UI", en: "UI"},
  site: {jp: "サイト", en: "Site"},
  project: {jp: "プロジェクト", en: "Project"},
  property: {jp: "プロパティ", en: "Property"},
  resetting: {jp: "再設定", en: "Resetting"},
  release: {jp: "公開", en: "Release"},
  immediate: {jp: "即時", en: "Immediate"},
  execution: {jp: "実行", en: "Execution"},
  reserve: {jp: "予約", en: "Reserve"},
  actions: {jp: "アクション", en: "Actions"},
  status: {jp: "ステータス", en: "Status"},
  checking: {jp: "確認中", en: "Checking"},
  task: {jp: "タスク", en: "Task"},
  conclusion: {jp: "状態", en: "Conclusion"},
  thumbnail: {jp: "サムネイル", en: "Thumbnail"},
  redirect: {jp: "リダイレクト", en: "redirect"},
  empty: {jp: "空", en: "empty"},
  copy: {jp: "コピー", en: "Copy"},
  before: {jp: "直前", en: "Before"},
  after: {jp: "直後", en: "After"},
  profile: {jp: "プロファイル", en: "Profile"},
  result: {jp: "Result", en: "Result"},
  file: {jp: "ファイル", en: "file"},
  mime: {jp: "MIME", en: "MIME"},
  quality: {jp: "圧縮率", en: "Quality"},
  width: {jp: "横幅", en: "Width"},
  height: {jp: "高さ", en: "Height"},
  centerPoint: {jp: "中心点", en: "Center Point"},
  horizontal: {jp: "横", en: "horizontal"},
  vertical: {jp: "縦", en: "vertical"},
  top: {jp: "上", en: "top"},
  middle: {jp: "中央", en: "middle"},
  bottom: {jp: "下", en: "bottom"},
  uid: {jp: "ユーザーID", en: "uid"},
  updated: {jp: "更新内容", en: "updated"},
  log: {jp: "ログ", en: "Log"},
  label: {jp: "ラベル", en: "Label"},
  target: {jp: "ターゲット", en: "Target"},
  basic: {jp: "基本", en: "Basic"},
  notSet: {jp: "未設定", en: "not set"},
  headline: {jp: "見出し", en: "Headline"},
  level: {jp: "レベル", en: "Level"},
  row: {jp: "行", en: "Row"},
  column: {jp: "列", en: "Column"},
  memo: {jp: "メモ", en: "memo"},
  update: {jp: "更新", en: "update"},
  request: {jp: "リクエスト", en: "request"},
  response: {jp: "レスポンス", en: "response"},
  error: {jp: "エラー", en: "error"},
  analysis: {jp: "解析", en: "analysis"},
  donot: {jp: "否", en: "Do not"},
  link: {jp: "リンク", en: "Link"},
  number: {jp: '数字', en: 'Number'},
  main: {jp: 'メイン', en: 'Main'},
  visual: {jp: 'ビジュアル', en: 'Visual'},
  block: {jp: 'ブロック', en: 'block'},
  justify: {jp: '配置', en: 'justify'},

  TF: {jp: "", en: ""},
};

for (let id in Vue.prototype.$words
  ) {
  //@ts-ignore
  Vue.prototype.$words[id] = Vue.prototype.$words[id][Vue.prototype.$lang];
}
Vue.prototype.$words.TF = (flag: Boolean) => {
  return flag ? Vue.prototype.$words.true : Vue.prototype.$words.false;
};
