name: CI-Firebase-hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '12.x'
          #- run: npm install
          #- run: npm run build
#      - run: npm i
      - run: FIRESTORE_PW=$FIRESTORE_PW npm run gen
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIRESTORE_PW: ${{ secrets.FIRESTORE_PW }}
      - run: ./node_modules/.bin/firebase deploy --only:hosting --token=$FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIRESTORE_PW: ${{ secrets.FIRESTORE_PW }}
